# Generated by Django 5.1.5 on 2025-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
