# Generated by Django 5.1.5 on 2025-11-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
