# Generated by Django 5.1.5 on 2025-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelimage_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
